development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: superstudio_test
  username: postgres
  password: Ld9Y6PE64

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: superstudio_test
  username: postgres
  password: Ld9Y6PE64